[server]
# Required for running behind Render's reverse proxy
enableXsrfProtection = false
enableCORS = false
headless = true
maxUploadSize = 50
maxMessageSize = 200
enableWebsocketCompression = false
